
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "./Silk The Song 1.0.0.mrpack"
      MEMORY: "6G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "Tundrapolis123"
    volumes:
      - ./data:/data
    restart: unless-stopped