#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 30 01:46:32 MST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=
